---
# tasks file for ldap
- name: Install the openldap and required Packages
  yum:
    name: "{{ ldap_server_pkgs }}"
    state: installed

- name: Delete the configuration directory
  file: 
    path: "{{ ldap_server_app_path }}/slapd.d"
    state: absent

- name: Generate the root password for ldap
  shell: slappasswd -s {{ ldap_server_rootpw }} 
  register: root_password

- name: "Add the user {{ ldap_server_user }}"
  user:
    name: "{{ ldap_server_user }}"
    shell: /bin/bash
    groups: "{{ ldap_server_user }}"
    state: present



- name: ensure the ldap database directory exists
  file:
    path: "/var/lib/ldap/{{ ldap_server_domain_name }}/"
    state: directory
    owner: "{{ ldap_server_user }}"
    group: "{{ ldap_server_user }}"


- name: Copy the slapd.conf configuration file for Redhat
  template:
    src: slapd.conf.j2
    dest: "{{ ldap_server_app_path }}/slapd.conf"
  notify: 
   - restart slapd

- name: Copy the ldap.conf configuration file
  template:
    src: ldap.conf.j2
    dest: "{{ ldap_server_app_path }}/ldap.conf"

